services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  calorie_estimator:
    build: .
    container_name: calorie_estimator
    env_file: .env
    privileged: true
    ports:
      - "24000:24000"
    depends_on:
      - mongodb
    
  streamlit_ui:
    build: ui/
    container_name: streamlit_ui
    privileged: true
    ports:
      - "8501:8501"
    depends_on:
      - calorie_estimator

volumes:
  mongo_data: